name: kyma function deployment

on:
  push:
    branches:
    - master
    paths:
    - 'lambdas/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@master
    - name: Get changed files
      id: file_changes
      uses: trilom/file-changes-action@v1
      with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: list changed files  
      run: |
        echo "----added files----"
        echo '${{ steps.file_changes.outputs.files_added}}'
        echo "----modified files----"
        echo '${{ steps.file_changes.outputs.files_modified}}'
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
    - run: npm install  
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        files: lambdas/*/*.js
    - name: Generate the deployment yamls
      run: |
        npm run deploymentByDirChanges
    - name: Deploy function to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply $K_DEPLOYMENT_STR
    - name: Save deployment result artifact  
      uses: actions/upload-artifact@v1
      with:
        name: deployment.yaml
        path: ./build/deployments

